/*
 * File: app/store/clausSistema.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.store.clausSistema', {
    extend: 'Ext.data.Store',
    alias: 'store.claussistema',

    requires: [
        'LECTCOMP.model.clausModel'
    ],

    config: {
        data: [
            {
                id: 1,
                clau: 'ecros84'
            },
            {
                id: 2,
                clau: 'carbon600'
            },
            {
                id: 3,
                clau: 'vidi'
            }
        ],
        model: 'LECTCOMP.model.clausModel',
        storeId: 'clausSystem'
    }
});