/*
 * File: app/store/vialerStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.store.vialerStore', {
    extend: 'Ext.data.Store',
    alias: 'store.vialerstore',

    requires: [
        'LECTCOMP.model.vialerModel'
    ],

    config: {
        data: [
            {
                idCarrer: 1,
                codiCarrer: '00179',
                nomCarrer: 'ALBEREDES (DE LES)',
                nomCarrerVia: 'CM ALBEREDES (DE LES)'
            },
            {
                idCarrer: 2,
                codiCarrer: '00098',
                nomCarrer: 'ALCOLEA DEL PINAR (D\')',
                nomCarrerVia: 'CA ALCOLEA DEL PINAR (D\')'
            },
            {
                idCarrer: 3,
                codiCarrer: '00014',
                nomCarrer: 'ALFORJA (D\')',
                nomCarrerVia: 'RR ALFORJA (D\')'
            },
            {
                idCarrer: 4,
                codiCarrer: '00022',
                nomCarrer: 'ANTONI GAUDI (D\')',
                nomCarrerVia: 'CR ANTONI GAUDI (D\')'
            },
            {
                idCarrer: 5,
                codiCarrer: '00153',
                nomCarrer: 'ARBRE (DE L\')',
                nomCarrerVia: 'PL ARBRE (DE L\')'
            },
            {
                idCarrer: 6,
                codiCarrer: '00001',
                nomCarrer: 'ARENAL (DE L\')',
                nomCarrerVia: 'CR ARENAL (DE L\')'
            },
            {
                idCarrer: 7,
                codiCarrer: '00140',
                nomCarrer: 'ARENES (LES)',
                nomCarrerVia: 'PA ARENES (LES)'
            },
            {
                idCarrer: 8,
                codiCarrer: '00011',
                nomCarrer: 'ARNAU DE PALOMAR',
                nomCarrerVia: 'PL ARNAU DE PALOMAR'
            },
            {
                idCarrer: 9,
                codiCarrer: '00077',
                nomCarrer: 'AVELLANERS (DELS)',
                nomCarrerVia: 'CR AVELLANERS (DELS)'
            },
            {
                idCarrer: 10,
                codiCarrer: '00002',
                nomCarrer: 'BAIX CAMP (DEL)',
                nomCarrerVia: 'TV BAIX CAMP (DEL)'
            },
            {
                idCarrer: 11,
                codiCarrer: '00172',
                nomCarrer: 'BAIX EBRE (DEL)',
                nomCarrerVia: 'CR BAIX EBRE (DEL)'
            },
            {
                idCarrer: 12,
                codiCarrer: '00116',
                nomCarrer: 'BALTASAR DE TODA  (DE)',
                nomCarrerVia: 'CR BALTASAR DE TODA  (DE)'
            },
            {
                idCarrer: 13,
                codiCarrer: '00003',
                nomCarrer: 'BARCELONA (DE)',
                nomCarrerVia: 'CR BARCELONA (DE)'
            },
            {
                idCarrer: 14,
                codiCarrer: '00138',
                nomCarrer: 'BARRIACH (EL)',
                nomCarrerVia: 'PA BARRIACH (EL)'
            },
            {
                idCarrer: 15,
                codiCarrer: '00004',
                nomCarrer: 'BEAT BONAVENTURA (DEL)',
                nomCarrerVia: 'CR BEAT BONAVENTURA (DEL)'
            },
            {
                idCarrer: 16,
                codiCarrer: '00139',
                nomCarrer: 'BLANCAFORT',
                nomCarrerVia: 'PA BLANCAFORT'
            },
            {
                idCarrer: 17,
                codiCarrer: '00089',
                nomCarrer: 'BLANCAFORT (DE)',
                nomCarrerVia: 'CM BLANCAFORT (DE)'
            },
            {
                idCarrer: 18,
                codiCarrer: '00005',
                nomCarrer: 'BORGES DEL CAMP (DE LES)',
                nomCarrerVia: 'CR BORGES DEL CAMP (DE LES)'
            },
            {
                idCarrer: 19,
                codiCarrer: '00163',
                nomCarrer: 'BOTARELL (DE)',
                nomCarrerVia: 'CM BOTARELL (DE)'
            },
            {
                idCarrer: 20,
                codiCarrer: '00119',
                nomCarrer: 'BURGAR (DEL)',
                nomCarrerVia: 'CM BURGAR (DEL)'
            },
            {
                idCarrer: 21,
                codiCarrer: '00135',
                nomCarrer: 'BURGAR (EL)',
                nomCarrerVia: 'PA BURGAR (EL)'
            },
            {
                idCarrer: 22,
                codiCarrer: '00006',
                nomCarrer: 'CAMBRILS (DE)',
                nomCarrerVia: 'CR CAMBRILS (DE)'
            },
            {
                idCarrer: 23,
                codiCarrer: '00025',
                nomCarrer: 'CAMBRILS (DE)',
                nomCarrerVia: 'CA CAMBRILS (DE)'
            },
            {
                idCarrer: 24,
                codiCarrer: '00158',
                nomCarrer: 'CAMPAS (EL)',
                nomCarrerVia: 'PA CAMPAS (EL)'
            },
            {
                idCarrer: 25,
                codiCarrer: '00128',
                nomCarrer: 'CASTELL NOU (EL)',
                nomCarrerVia: 'PA CASTELL NOU (EL)'
            },
            {
                idCarrer: 26,
                codiCarrer: '00100',
                nomCarrer: 'CASTELLVELL (DE)',
                nomCarrerVia: 'CM CASTELLVELL (DE)'
            },
            {
                idCarrer: 27,
                codiCarrer: '00093',
                nomCarrer: 'CATALANS (DELS)',
                nomCarrerVia: 'CM CATALANS (DELS)'
            },
            {
                idCarrer: 28,
                codiCarrer: '00009',
                nomCarrer: 'CATALUNYA (DE)',
                nomCarrerVia: 'AV CATALUNYA (DE)'
            },
            {
                idCarrer: 29,
                codiCarrer: '00086',
                nomCarrer: 'CERDANS (DELS)',
                nomCarrerVia: 'CM CERDANS (DELS)'
            },
            {
                idCarrer: 30,
                codiCarrer: '00132',
                nomCarrer: 'CLOTA (LA)',
                nomCarrerVia: 'PA CLOTA (LA)'
            },
            {
                idCarrer: 31,
                codiCarrer: '00095',
                nomCarrer: 'COLL DEL BOC (DEL)',
                nomCarrerVia: 'CM COLL DEL BOC (DEL)'
            },
            {
                idCarrer: 32,
                codiCarrer: '00108',
                nomCarrer: 'COMES D\'ULLDEMOLINS (LES)',
                nomCarrerVia: 'PA COMES D\'ULLDEMOLINS (LES)'
            },
            {
                idCarrer: 33,
                codiCarrer: '00175',
                nomCarrer: 'CONCA DE BARBERA (DE LA)',
                nomCarrerVia: 'CR CONCA DE BARBERA (DE LA)'
            },
            {
                idCarrer: 34,
                codiCarrer: '00160',
                nomCarrer: 'DEVESES (DE LES)',
                nomCarrerVia: 'CM DEVESES (DE LES)'
            },
            {
                idCarrer: 35,
                codiCarrer: '00117',
                nomCarrer: 'ENAMORATS (DELS)',
                nomCarrerVia: 'TV ENAMORATS (DELS)'
            },
            {
                idCarrer: 36,
                codiCarrer: '00151',
                nomCarrer: 'ENRIC CASTRO I C.(D\')',
                nomCarrerVia: 'CR ENRIC CASTRO I C.(D\')'
            },
            {
                idCarrer: 37,
                codiCarrer: '00015',
                nomCarrer: 'ESGLESIA (DE L\')',
                nomCarrerVia: 'PL ESGLESIA (DE L\')'
            },
            {
                idCarrer: 38,
                codiCarrer: '00016',
                nomCarrer: 'FADRINS (DELS)',
                nomCarrerVia: 'TV FADRINS (DELS)'
            },
            {
                idCarrer: 39,
                codiCarrer: '00017',
                nomCarrer: 'FERRANT',
                nomCarrerVia: 'CR FERRANT'
            },
            {
                idCarrer: 40,
                codiCarrer: '00018',
                nomCarrer: 'FONT (DE LA)',
                nomCarrerVia: 'TV FONT (DE LA)'
            },
            {
                idCarrer: 41,
                codiCarrer: '00084',
                nomCarrer: 'FONT DEL ROS (DE LA)',
                nomCarrerVia: 'CM FONT DEL ROS (DE LA)'
            },
            {
                idCarrer: 42,
                codiCarrer: '00131',
                nomCarrer: 'FONT LLONGA (LA)',
                nomCarrerVia: 'PA FONT LLONGA (LA)'
            },
            {
                idCarrer: 43,
                codiCarrer: '00155',
                nomCarrer: 'FONT LLONGA (LA)',
                nomCarrerVia: 'PA FONT LLONGA (LA)'
            },
            {
                idCarrer: 44,
                codiCarrer: '00127',
                nomCarrer: 'FORANELL (DEL)',
                nomCarrerVia: 'CR FORANELL (DEL)'
            },
            {
                idCarrer: 45,
                codiCarrer: '00075',
                nomCarrer: 'FRANCESC  MACIA (DE)',
                nomCarrerVia: 'AV FRANCESC  MACIA (DE)'
            },
            {
                idCarrer: 46,
                codiCarrer: '00149',
                nomCarrer: 'FRANCESC DE P. QUINTANA',
                nomCarrerVia: 'CR FRANCESC DE P. QUINTANA'
            },
            {
                idCarrer: 47,
                codiCarrer: '00076',
                nomCarrer: 'FREIXE (DEL)',
                nomCarrerVia: 'CR FREIXE (DEL)'
            },
            {
                idCarrer: 48,
                codiCarrer: '00129',
                nomCarrer: 'FREIXE (EL)',
                nomCarrerVia: 'PA FREIXE (EL)'
            },
            {
                idCarrer: 49,
                codiCarrer: '00079',
                nomCarrer: 'FUTBOL (DEL)',
                nomCarrerVia: 'CR FUTBOL (DEL)'
            },
            {
                idCarrer: 50,
                codiCarrer: '00020',
                nomCarrer: 'GALANES (DE LES)',
                nomCarrerVia: 'CR GALANES (DE LES)'
            },
            {
                idCarrer: 51,
                codiCarrer: '00021',
                nomCarrer: 'GARBI (DEL)',
                nomCarrerVia: 'CR GARBI (DEL)'
            },
            {
                idCarrer: 52,
                codiCarrer: '00170',
                nomCarrer: 'GEGANTS (DELS)',
                nomCarrerVia: 'PL GEGANTS (DELS)'
            },
            {
                idCarrer: 53,
                codiCarrer: '00070',
                nomCarrer: 'GERMANS NEBOT (DELS)',
                nomCarrerVia: 'PG GERMANS NEBOT (DELS)'
            },
            {
                idCarrer: 54,
                codiCarrer: '00023',
                nomCarrer: 'GREGAL (DEL)',
                nomCarrerVia: 'CR GREGAL (DEL)'
            },
            {
                idCarrer: 55,
                codiCarrer: '00133',
                nomCarrer: 'HORTA NOVA (L\')',
                nomCarrerVia: 'PA HORTA NOVA (L\')'
            },
            {
                idCarrer: 56,
                codiCarrer: '00180',
                nomCarrer: 'HORTETS (DELS)',
                nomCarrerVia: 'CR HORTETS (DELS)'
            },
            {
                idCarrer: 57,
                codiCarrer: '00091',
                nomCarrer: 'HOSPITALET-MAS SEDO',
                nomCarrerVia: 'CA HOSPITALET-MAS SEDO'
            },
            {
                idCarrer: 58,
                codiCarrer: '00171',
                nomCarrer: 'INFORMATICA (DE LA)',
                nomCarrerVia: 'CR INFORMATICA (DE LA)'
            },
            {
                idCarrer: 59,
                codiCarrer: '00152',
                nomCarrer: 'JACINT VERDAGUER (DE)',
                nomCarrerVia: 'CR JACINT VERDAGUER (DE)'
            },
            {
                idCarrer: 60,
                codiCarrer: '00137',
                nomCarrer: 'JOAN BERGOS MASSO (DE)',
                nomCarrerVia: 'CR JOAN BERGOS MASSO (DE)'
            },
            {
                idCarrer: 61,
                codiCarrer: '00027',
                nomCarrer: 'JOAN MARAGALL (DE)',
                nomCarrerVia: 'TV JOAN MARAGALL (DE)'
            },
            {
                idCarrer: 62,
                codiCarrer: '00080',
                nomCarrer: 'JOAN MIRO (DE)',
                nomCarrerVia: 'CR JOAN MIRO (DE)'
            },
            {
                idCarrer: 63,
                codiCarrer: '00046',
                nomCarrer: 'JOAN SALVADO BADIA (DE)',
                nomCarrerVia: 'CR JOAN SALVADO BADIA (DE)'
            },
            {
                idCarrer: 64,
                codiCarrer: '00167',
                nomCarrer: 'JOSEP M. FOLCH I TORRES (DE)',
                nomCarrerVia: 'CR JOSEP M. FOLCH I TORRES (DE)'
            },
            {
                idCarrer: 65,
                codiCarrer: '00061',
                nomCarrer: 'JOSEP M. SENTIS (DE)',
                nomCarrerVia: 'AV JOSEP M. SENTIS (DE)'
            },
            {
                idCarrer: 66,
                codiCarrer: '00031',
                nomCarrer: 'JOSEP MASSO AGUILO (DE)',
                nomCarrerVia: 'CR JOSEP MASSO AGUILO (DE)'
            },
            {
                idCarrer: 67,
                codiCarrer: '00118',
                nomCarrer: 'LLEBEIG (DEL)',
                nomCarrerVia: 'CR LLEBEIG (DEL)'
            },
            {
                idCarrer: 68,
                codiCarrer: '00024',
                nomCarrer: 'LLEVANT (DEL)',
                nomCarrerVia: 'CR LLEVANT (DEL)'
            },
            {
                idCarrer: 69,
                codiCarrer: '00136',
                nomCarrer: 'LLUIS COMPANYS I JOVER',
                nomCarrerVia: 'CR LLUIS COMPANYS I JOVER'
            },
            {
                idCarrer: 70,
                codiCarrer: '00026',
                nomCarrer: 'MAJOR',
                nomCarrerVia: 'CR MAJOR'
            },
            {
                idCarrer: 71,
                codiCarrer: '00028',
                nomCarrer: 'MARE CELIA PINO (DE LA)',
                nomCarrerVia: 'PL MARE CELIA PINO (DE LA)'
            },
            {
                idCarrer: 72,
                codiCarrer: '00029',
                nomCarrer: 'MARINADA (DE LA)',
                nomCarrerVia: 'CR MARINADA (DE LA)'
            },
            {
                idCarrer: 73,
                codiCarrer: '00156',
                nomCarrer: 'MARRADA (LA)',
                nomCarrerVia: 'PA MARRADA (LA)'
            },
            {
                idCarrer: 74,
                codiCarrer: '00134',
                nomCarrer: 'MAS DE GOMANDI (EL)',
                nomCarrerVia: 'PA MAS DE GOMANDI (EL)'
            },
            {
                idCarrer: 75,
                codiCarrer: '00019',
                nomCarrer: 'MAS DE MINFLO (DEL)',
                nomCarrerVia: 'CM MAS DE MINFLO (DEL)'
            },
            {
                idCarrer: 76,
                codiCarrer: '00150',
                nomCarrer: 'MAS DE N\'ALBI (DE)',
                nomCarrerVia: 'PA MAS DE N\'ALBI (DE)'
            },
            {
                idCarrer: 77,
                codiCarrer: '00125',
                nomCarrer: 'MAS DE PAGES (DEL)',
                nomCarrerVia: 'CM MAS DE PAGES (DEL)'
            },
            {
                idCarrer: 78,
                codiCarrer: '00168',
                nomCarrer: 'MAS DE PAGES (DEL)',
                nomCarrerVia: 'CM MAS DE PAGES (DEL)'
            },
            {
                idCarrer: 79,
                codiCarrer: '00161',
                nomCarrer: 'MAS DE REGIMENTS (DEL)',
                nomCarrerVia: 'CM MAS DE REGIMENTS (DEL)'
            },
            {
                idCarrer: 80,
                codiCarrer: '00090',
                nomCarrer: 'MAS DE SABATER (DEL)',
                nomCarrerVia: 'CM MAS DE SABATER (DEL)'
            },
            {
                idCarrer: 81,
                codiCarrer: '00105',
                nomCarrer: 'MAS DEL XULO (DEL)',
                nomCarrerVia: 'CM MAS DEL XULO (DEL)'
            },
            {
                idCarrer: 82,
                codiCarrer: '00088',
                nomCarrer: 'MAS GASET (DEL)',
                nomCarrerVia: 'CM MAS GASET (DEL)'
            },
            {
                idCarrer: 83,
                codiCarrer: '00147',
                nomCarrer: 'MAS LIBORI (DEL)',
                nomCarrerVia: 'CR MAS LIBORI (DEL)'
            },
            {
                idCarrer: 84,
                codiCarrer: '00030',
                nomCarrer: 'MASFERRER (DE)',
                nomCarrerVia: 'CR MASFERRER (DE)'
            },
            {
                idCarrer: 85,
                codiCarrer: '00162',
                nomCarrer: 'MASPUJOLS (DE)',
                nomCarrerVia: 'CA MASPUJOLS (DE)'
            },
            {
                idCarrer: 86,
                codiCarrer: '00102',
                nomCarrer: 'MASPUJOLS (DE)',
                nomCarrerVia: 'RR MASPUJOLS (DE)'
            },
            {
                idCarrer: 87,
                codiCarrer: '00094',
                nomCarrer: 'MATXOS (DELS)',
                nomCarrerVia: 'CM MATXOS (DELS)'
            },
            {
                idCarrer: 88,
                codiCarrer: '00121',
                nomCarrer: 'MERCE RODOREDA (DE LA)',
                nomCarrerVia: 'CR MERCE RODOREDA (DE LA)'
            },
            {
                idCarrer: 89,
                codiCarrer: '00032',
                nomCarrer: 'MESTRAL (DEL)',
                nomCarrerVia: 'CR MESTRAL (DEL)'
            },
            {
                idCarrer: 90,
                codiCarrer: '00033',
                nomCarrer: 'MIGJORN (DEL)',
                nomCarrerVia: 'CR MIGJORN (DEL)'
            },
            {
                idCarrer: 91,
                codiCarrer: '00115',
                nomCarrer: 'MOLA (DE LA)',
                nomCarrerVia: 'CR MOLA (DE LA)'
            },
            {
                idCarrer: 92,
                codiCarrer: '00097',
                nomCarrer: 'MOLI DE VENT (DEL)',
                nomCarrerVia: 'CM MOLI DE VENT (DEL)'
            },
            {
                idCarrer: 93,
                codiCarrer: '00123',
                nomCarrer: 'MOLINS NOUS (DELS)',
                nomCarrerVia: 'CR MOLINS NOUS (DELS)'
            },
            {
                idCarrer: 94,
                codiCarrer: '00101',
                nomCarrer: 'MOLINS NOUS (DELS)',
                nomCarrerVia: 'CM MOLINS NOUS (DELS)'
            },
            {
                idCarrer: 95,
                codiCarrer: '00035',
                nomCarrer: 'MONT-ROIG (DE)',
                nomCarrerVia: 'CR MONT-ROIG (DE)'
            },
            {
                idCarrer: 96,
                codiCarrer: '00114',
                nomCarrer: 'MONT-ROIG (DE)',
                nomCarrerVia: 'TV MONT-ROIG (DE)'
            },
            {
                idCarrer: 97,
                codiCarrer: '00034',
                nomCarrer: 'MONTBRIO (DE)',
                nomCarrerVia: 'AV MONTBRIO (DE)'
            },
            {
                idCarrer: 98,
                codiCarrer: '00078',
                nomCarrer: 'MORERES (DE LES)',
                nomCarrerVia: 'CR MORERES (DE LES)'
            },
            {
                idCarrer: 99,
                codiCarrer: '00036',
                nomCarrer: 'MURALLA DE LA FONT',
                nomCarrerVia: 'CR MURALLA DE LA FONT'
            },
            {
                idCarrer: 100,
                codiCarrer: '00166',
                nomCarrer: 'MUSICA (DE LA)',
                nomCarrerVia: 'CR MUSICA (DE LA)'
            },
            {
                idCarrer: 101,
                codiCarrer: '00037',
                nomCarrer: 'NOU',
                nomCarrerVia: 'CR NOU'
            },
            {
                idCarrer: 102,
                codiCarrer: '00038',
                nomCarrer: 'OEST (DE L\')',
                nomCarrerVia: 'CR OEST (DE L\')'
            },
            {
                idCarrer: 103,
                codiCarrer: '00039',
                nomCarrer: 'OM (DE L\')',
                nomCarrerVia: 'PL OM (DE L\')'
            },
            {
                idCarrer: 104,
                codiCarrer: '00040',
                nomCarrer: 'ORATGELL (DE L\')',
                nomCarrerVia: 'PL ORATGELL (DE L\')'
            },
            {
                idCarrer: 105,
                codiCarrer: '00165',
                nomCarrer: 'PASSERES (DE LES)',
                nomCarrerVia: 'CM PASSERES (DE LES)'
            },
            {
                idCarrer: 106,
                codiCarrer: '00008',
                nomCarrer: 'PAU CASALS (DE)',
                nomCarrerVia: 'AV PAU CASALS (DE)'
            },
            {
                idCarrer: 107,
                codiCarrer: '00082',
                nomCarrer: 'PINS (DELS)',
                nomCarrerVia: 'CR PINS (DELS)'
            },
            {
                idCarrer: 108,
                codiCarrer: '00146',
                nomCarrer: 'PLA PARCIAL INDUSTRIAL',
                nomCarrerVia: 'LG PLA PARCIAL INDUSTRIAL'
            },
            {
                idCarrer: 109,
                codiCarrer: '00145',
                nomCarrer: 'PLA PARCIAL RESIDENCIAL',
                nomCarrerVia: 'LG PLA PARCIAL RESIDENCIAL'
            },
            {
                idCarrer: 110,
                codiCarrer: '00176',
                nomCarrer: 'PLANES (DE LES)',
                nomCarrerVia: 'AV PLANES (DE LES)'
            },
            {
                idCarrer: 111,
                codiCarrer: '00130',
                nomCarrer: 'PLANES DEL ROQUIS (LES)',
                nomCarrerVia: 'PA PLANES DEL ROQUIS (LES)'
            },
            {
                idCarrer: 112,
                codiCarrer: '00143',
                nomCarrer: 'POLIGON',
                nomCarrerVia: 'LG POLIGON'
            },
            {
                idCarrer: 113,
                codiCarrer: '00042',
                nomCarrer: 'PORTAL DE PONENT (DEL)',
                nomCarrerVia: 'PL PORTAL DE PONENT (DEL)'
            },
            {
                idCarrer: 114,
                codiCarrer: '00043',
                nomCarrer: 'POU (DEL)',
                nomCarrerVia: 'PL POU (DEL)'
            },
            {
                idCarrer: 115,
                codiCarrer: '00142',
                nomCarrer: 'PRAT (DEL)',
                nomCarrerVia: 'AV PRAT (DEL)'
            },
            {
                idCarrer: 116,
                codiCarrer: '00141',
                nomCarrer: 'PRAT (EL)',
                nomCarrerVia: 'PA PRAT (EL)'
            },
            {
                idCarrer: 117,
                codiCarrer: '00174',
                nomCarrer: 'PRIORAT (DEL)',
                nomCarrerVia: 'CR PRIORAT (DEL)'
            },
            {
                idCarrer: 118,
                codiCarrer: '00081',
                nomCarrer: 'PUIG PEDROS (EL)',
                nomCarrerVia: 'PA PUIG PEDROS (EL)'
            },
            {
                idCarrer: 119,
                codiCarrer: '00104',
                nomCarrer: 'RECREO (DEL)',
                nomCarrerVia: 'CM RECREO (DEL)'
            },
            {
                idCarrer: 120,
                codiCarrer: '00120',
                nomCarrer: 'REMEI (DEL)',
                nomCarrerVia: 'CM REMEI (DEL)'
            },
            {
                idCarrer: 121,
                codiCarrer: '00044',
                nomCarrer: 'REUS (DE)',
                nomCarrerVia: 'AV REUS (DE)'
            },
            {
                idCarrer: 122,
                codiCarrer: '00083',
                nomCarrer: 'REUS-CAMBRILS',
                nomCarrerVia: 'CA REUS-CAMBRILS'
            },
            {
                idCarrer: 123,
                codiCarrer: '00173',
                nomCarrer: 'RIBERA D\'EBRE (DE LA)',
                nomCarrerVia: 'CR RIBERA D\'EBRE (DE LA)'
            },
            {
                idCarrer: 124,
                codiCarrer: '00013',
                nomCarrer: 'RIERO (quin riero)',
                nomCarrerVia: 'AY RIERO (quin riero)'
            },
            {
                idCarrer: 125,
                codiCarrer: '00096',
                nomCarrer: 'RIUDOMS-BORGES DEL CAMP',
                nomCarrerVia: 'CA RIUDOMS-BORGES DEL CAMP'
            },
            {
                idCarrer: 126,
                codiCarrer: '00007',
                nomCarrer: 'RIUDOMS-CAMBRILS',
                nomCarrerVia: 'CA RIUDOMS-CAMBRILS'
            },
            {
                idCarrer: 127,
                codiCarrer: '00092',
                nomCarrer: 'RIUDOMS-MONTBRIO',
                nomCarrerVia: 'CA RIUDOMS-MONTBRIO'
            },
            {
                idCarrer: 128,
                codiCarrer: '00109',
                nomCarrer: 'RIUDOMS-REUS',
                nomCarrerVia: 'CA RIUDOMS-REUS'
            },
            {
                idCarrer: 129,
                codiCarrer: '00085',
                nomCarrer: 'RIUDOMS-VINYOLS',
                nomCarrerVia: 'CA RIUDOMS-VINYOLS'
            },
            {
                idCarrer: 130,
                codiCarrer: '00010',
                nomCarrer: 'RODOLF CAVALLE TOMAS (DE)',
                nomCarrerVia: 'CR RODOLF CAVALLE TOMAS (DE)'
            },
            {
                idCarrer: 131,
                codiCarrer: '00099',
                nomCarrer: 'ROQUIS (DEL)',
                nomCarrerVia: 'CM ROQUIS (DEL)'
            },
            {
                idCarrer: 132,
                codiCarrer: '00126',
                nomCarrer: 'ROVIRA (D\'EN)',
                nomCarrerVia: 'CR ROVIRA (D\'EN)'
            },
            {
                idCarrer: 133,
                codiCarrer: '00124',
                nomCarrer: 'SALVADOR ESPRIU (DE)',
                nomCarrerVia: 'CR SALVADOR ESPRIU (DE)'
            },
            {
                idCarrer: 134,
                codiCarrer: '00047',
                nomCarrer: 'SANT ANTONI (DE)',
                nomCarrerVia: 'CR SANT ANTONI (DE)'
            },
            {
                idCarrer: 135,
                codiCarrer: '00144',
                nomCarrer: 'SANT ANTONI (DE)',
                nomCarrerVia: 'PL SANT ANTONI (DE)'
            },
            {
                idCarrer: 136,
                codiCarrer: '00048',
                nomCarrer: 'SANT BONIFACI (DE)',
                nomCarrerVia: 'CR SANT BONIFACI (DE)'
            },
            {
                idCarrer: 137,
                codiCarrer: '00178',
                nomCarrer: 'SANT DOMINGO (DE)',
                nomCarrerVia: 'CM SANT DOMINGO (DE)'
            },
            {
                idCarrer: 138,
                codiCarrer: '00049',
                nomCarrer: 'SANT FRANCESC (DE)',
                nomCarrerVia: 'AR SANT FRANCESC (DE)'
            },
            {
                idCarrer: 139,
                codiCarrer: '00050',
                nomCarrer: 'SANT ISIDRE (DE)',
                nomCarrerVia: 'CR SANT ISIDRE (DE)'
            },
            {
                idCarrer: 140,
                codiCarrer: '00051',
                nomCarrer: 'SANT JAUME (DE)',
                nomCarrerVia: 'CR SANT JAUME (DE)'
            },
            {
                idCarrer: 141,
                codiCarrer: '00052',
                nomCarrer: 'SANT JOAN (DE)',
                nomCarrerVia: 'CR SANT JOAN (DE)'
            },
            {
                idCarrer: 142,
                codiCarrer: '00053',
                nomCarrer: 'SANT JOSEP (DE)',
                nomCarrerVia: 'CR SANT JOSEP (DE)'
            },
            {
                idCarrer: 143,
                codiCarrer: '00054',
                nomCarrer: 'SANT JULIA (DE)',
                nomCarrerVia: 'CR SANT JULIA (DE)'
            },
            {
                idCarrer: 144,
                codiCarrer: '00055',
                nomCarrer: 'SANT MARC (DE)',
                nomCarrerVia: 'CR SANT MARC (DE)'
            },
            {
                idCarrer: 145,
                codiCarrer: '00056',
                nomCarrer: 'SANT PAU (DE)',
                nomCarrerVia: 'CR SANT PAU (DE)'
            },
            {
                idCarrer: 146,
                codiCarrer: '00107',
                nomCarrer: 'SANT PAU (DE)',
                nomCarrerVia: 'CM SANT PAU (DE)'
            },
            {
                idCarrer: 147,
                codiCarrer: '00057',
                nomCarrer: 'SANT PERE (DE)',
                nomCarrerVia: 'CR SANT PERE (DE)'
            },
            {
                idCarrer: 148,
                codiCarrer: '00058',
                nomCarrer: 'SANT SEBASTIA (DE)',
                nomCarrerVia: 'CR SANT SEBASTIA (DE)'
            },
            {
                idCarrer: 149,
                codiCarrer: '00059',
                nomCarrer: 'SANT TOMAS (DE)',
                nomCarrerVia: 'CR SANT TOMAS (DE)'
            },
            {
                idCarrer: 150,
                codiCarrer: '00060',
                nomCarrer: 'SANT VICEN€ (DE)',
                nomCarrerVia: 'CR SANT VICEN€ (DE)'
            },
            {
                idCarrer: 151,
                codiCarrer: '00103',
                nomCarrer: 'SARDANA (DE LA)',
                nomCarrerVia: 'CR SARDANA (DE LA)'
            },
            {
                idCarrer: 152,
                codiCarrer: '00062',
                nomCarrer: 'SERE (DEL)',
                nomCarrerVia: 'CR SERE (DEL)'
            },
            {
                idCarrer: 153,
                codiCarrer: '00012',
                nomCarrer: 'SIR ALEXANDER FLEMING',
                nomCarrerVia: 'CR SIR ALEXANDER FLEMING'
            },
            {
                idCarrer: 154,
                codiCarrer: '00148',
                nomCarrer: 'SOLANA (DE LA)',
                nomCarrerVia: 'CR SOLANA (DE LA)'
            },
            {
                idCarrer: 155,
                codiCarrer: '00154',
                nomCarrer: 'SORTS (LES)',
                nomCarrerVia: 'PA SORTS (LES)'
            },
            {
                idCarrer: 156,
                codiCarrer: '00157',
                nomCarrer: 'TARRAGONA (DE)',
                nomCarrerVia: 'CR TARRAGONA (DE)'
            },
            {
                idCarrer: 157,
                codiCarrer: '00087',
                nomCarrer: 'TARRAGONA (DE)',
                nomCarrerVia: 'CM TARRAGONA (DE)'
            },
            {
                idCarrer: 158,
                codiCarrer: '00177',
                nomCarrer: 'TARRAGONES (DEL)',
                nomCarrerVia: 'CR TARRAGONES (DEL)'
            },
            {
                idCarrer: 159,
                codiCarrer: '00066',
                nomCarrer: 'TERRAL (DEL)',
                nomCarrerVia: 'CR TERRAL (DEL)'
            },
            {
                idCarrer: 160,
                codiCarrer: '00067',
                nomCarrer: 'TRAMUNTANA (DE LA)',
                nomCarrerVia: 'CR TRAMUNTANA (DE LA)'
            },
            {
                idCarrer: 161,
                codiCarrer: '00159',
                nomCarrer: 'VELL DE LES BORGES A REUS',
                nomCarrerVia: 'CM VELL DE LES BORGES A REUS'
            },
            {
                idCarrer: 162,
                codiCarrer: '00069',
                nomCarrer: 'VERGE DE MONTSERRAT',
                nomCarrerVia: 'AV VERGE DE MONTSERRAT'
            },
            {
                idCarrer: 163,
                codiCarrer: '00068',
                nomCarrer: 'VERGE DELS DOLORS (DE LA)',
                nomCarrerVia: 'CR VERGE DELS DOLORS (DE LA)'
            },
            {
                idCarrer: 164,
                codiCarrer: '00169',
                nomCarrer: 'VIA ROMANA',
                nomCarrerVia: 'CR VIA ROMANA'
            },
            {
                idCarrer: 165,
                codiCarrer: '00071',
                nomCarrer: 'VINYOLS (DE)',
                nomCarrerVia: 'CR VINYOLS (DE)'
            },
            {
                idCarrer: 166,
                codiCarrer: '00073',
                nomCarrer: 'VINYOLS (DE)',
                nomCarrerVia: 'CA VINYOLS (DE)'
            },
            {
                idCarrer: 167,
                codiCarrer: '00164',
                nomCarrer: 'VINYOLS A TARRAGONA (DE)',
                nomCarrerVia: 'CM VINYOLS A TARRAGONA (DE)'
            },
            {
                idCarrer: 168,
                codiCarrer: '00074',
                nomCarrer: 'XALOC (DEL)',
                nomCarrerVia: 'CR XALOC (DEL)'
            }
        ],
        model: 'LECTCOMP.model.vialerModel',
        storeId: 'vialstore',
        grouper: {
            groupFn: function(record) {
                return record.get('nomCarrerVia')[3];
            }
        },
        sorters: {
            property: 'nomCarrer'
        }
    }
});