/*
 * File: app/view/panellLectures.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and every time you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.view.llistaSeleccio', {
    extend: 'Ext.Container',
	xtype: 'llistaSeleccio',
    config: {
    	id: 'llistaSeleccio',
    	items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        id: 'mytitlebar1',
                        itemId: '',
                        title: 'SELECCIONA'
                    },
                    {
                        xtype: 'label',
                        height: 46,
                        html: '',
                        id: 'textSelFeta'
                    },
                    {
                        xtype: 'list',
                        height: 384,
                        id: 'listSeleccio',
                        width: 318,
                        itemTpl: [
                            '<div><b>{nComptador} {llegit}</b></div>'
                        ],
                        store: 'llistaCompt'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                type: 'button',
                                centered: true,
                                itemId: 'mybutton5',
                                ui: 'back',
                                text: 'TORNAR A LA SELECCIÓ'
                            }
                        ]
                    }
                ] 
	}  
});