/*
 * File: app/view/panellCarregar.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.view.panellCarregar', {
    extend: 'Ext.Panel',
    xtype:'panellCarregar',

    config: {
        id: 'panellcarregar',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 57,
                title: 'CARREGAR TRIMESTRE'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 54,
                title: '',
                items: [
                    {
                        xtype: 'button',
                        centered: true,
                        id: 'btnCarregar',
                        itemId: '',
                        text: 'INICIAR PROCÉS'
                    }
                ]
            },
            {
                xtype: 'label',
                height: 120,
                html: '<p align="justify"> Aquest procediment esborrarà totes les dades introduides del trimestre acutal. <br /> <br />Introduiex el codi de seguretat per a carregar les dades  </p>',
                left: 5,
                top: 20,
                width: 309
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 198,
                id: '',
                items: [
                    {
                        xtype: 'passwordfield',
                        id: 'codiseguretat',
                        label: 'CODI',
                        name: 'codiSeguretat',
                        required: true
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBtnCarregarTap',
                event: 'tap',
                delegate: '#btnCarregar'
            }
        ]
    },

    onBtnCarregarTap: function(button, e, options) {
        var codi =  Ext.ComponentQuery.query('#codiseguretat')[0].getValue();
        var correcte=0;

        //Accedim a l'store per localitzar la clau de seguretat
        var store = Ext.data.StoreManager.lookup('clausSystem');

        for(var i = 0; i < store.getCount(); i++) {  
            if (store.getAt(i).get('clau') == codi){
                correcte=1;
            }
        }

        if (correcte===0){
            Ext.Msg.show({ title: 'Avís:',
                message: 'Codi Seguretat incorrecte',
                buttons:  [{text : 'Acceptar'}]});        
            } else {
                Ext.Msg.show({ title: 'Avís:',
                    message: 'Carrega completada correctament',
                    buttons:  [{text : 'Acceptar'}]});            
                }

                this.getParent().pop();
    }

});