/*
 * File: app/view/panellLectures.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.view.panellLectures', {
    extend: 'Ext.TabPanel',
	xtype: 'panellLectures',
	
	
	
    config: {
        itemTabActiu : 0,
        ui: '',
        items: [
            {
                xtype: 'container',
                title: 'Núm Comptador',
                ui: '',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        title: 'Introdueix el comptador'
                    },
                    {
                        xtype: 'textfield',
                        border: 5,
                        docked: 'top',
                        id: 'campNumComptador',
                        margin: '',
                        label: 'Número'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                centered: true,
                                itemId: 'mybutton4',
                                text: 'SELECCIONAR COMTPADOR/S'
                            }
                        ]
                    }
                ]
         },
         {
                        xtype: 'container',
                        title: 'Adreça Comptador',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                title: 'Selecciona adreça i núm.'
                            },
                            {
                                xtype: 'textfield',
                                border: 5,
                                docked: 'top',
                                id: 'nCarrer',
                                margin: '',
                                label: 'Número',
                                required: true
                            },
                            {
                                xtype: 'list',
                                docked: 'top',
                                height: 340,
                                id: 'listAdreca',
                                itemId: 'mylist1',
                                width: 320,
                                itemTpl: [
                                    '<div>{nomCarrerVia}</div>'
                                ],
                                store: 'vialstore',
                                grouped: true,
                                indexBar: true
                            }
                        ]
                    }
                ]
        ,
    listeners: [
    		{
                fn: 'onChangeTab',
                event: 'activeitemchange',
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onListAdrecaItemTap',
                event: 'itemtap',
                delegate: '#listAdreca'
            },
            {
                fn: 'onMybutton5Tap',
                event: 'tap',
                delegate: '#mybutton5'
            }
        ]
    },
    
    activeitemchange: function(component, value, oldValue, eOpts) {
    	debugger;
    	this.setItemTabActiu(value);
    },

    onMybutton4Tap: function(button, e, options) {
        //Quan hem introduit el número de comptador o entrat l'adreça
        //Ocultem el contenidor del selector de comptadors
        //I mostrem la llista de comptadors seleccionats.
        
        debugger;

        var tabulador = Ext.getCmp("selectorComptadors");
        var tabuladorActiu = this.getItemTabActiu();;

        if (tabuladorActiu===0) {
            //Tabulador Número de comptador 
            var nCompt =  Ext.ComponentQuery.query('#campNumComptador')[0].getValue();
            if (nCompt !== ''){

                storeComtpadors = Ext.data.StoreManager.lookup('llistaCompt');
                //Esborrem possibles filtres
                storeComtpadors.clearFilter();

                //Filtrem pel camp nComptador
                var thisRegEx = new RegExp(nCompt, "i");
                storeComtpadors.filterBy(function(record) {
                    if (thisRegEx.test(record.get('nComptador'))) {
                        return true;
                    }
                    return false;
                });
                debugger;
				Ext.ComponentQuery.query('inicialView').push({xtype:'llistaSeleccio'});
                //Ext.ComponentQuery.query('#selectorComptadors')[0].setHidden(true);
                //Ext.ComponentQuery.query('#llistaSeleccio')[0].setHidden(false);
                //Ext.ComponentQuery.query('#textSelFeta')[0].setHidden(true);
            } else {
                //No has introduit cap valor 
                Ext.Msg.show({ title: 'Avís:',
                    message: 'No has introduit cap Número ',
                    buttons:  [{text : 'Acceptar'}]}); 
                    this.refresh();

                }
            }
    },

    onListAdrecaItemTap: function(dataview, index, target, record, e, options) {
        var codCarrer=record.data.codiCarrer;
        var nomCar=record.data.nomCarrerVia;
        var numCarrer =  Ext.ComponentQuery.query('#nCarrer')[0].getValue();

        if (numCarrer !== ''){

            var sComtpadors = Ext.data.StoreManager.lookup('llistaCompt');
            //Esborrem possibles filtres
            sComtpadors.clearFilter();

            //Filtrem pel camp codiCarrer i numero    
            sComtpadors.filterBy(function(record, id) {
                if ((record.get('codiCarrer').match(codCarrer)) &&
                (record.get('numero').match(numCarrer))){
                    return true;
                } else {
                    return false;
                }
            });


            Ext.ComponentQuery.query('#selectorComptadors')[0].setHidden(true);
            Ext.ComponentQuery.query('#llistaSeleccio')[0].setHidden(false);    
            var h='<center><b>'+nomCar+'<br>Núm: '+numCarrer+'</b></center>';
            Ext.ComponentQuery.query('#textSelFeta')[0].setHtml(h);     
            Ext.ComponentQuery.query('#textSelFeta')[0].setHidden(false);


        } else {
            //No has introduit cap valor 
            Ext.Msg.show({ title: 'Avís:',
                message: 'No has introduit el número del bloc ',
                buttons:  [{text : 'Acceptar'}]}); 
                this.refresh();

            }

    },

    onMybutton5Tap: function(button, e, options) {
        Ext.ComponentQuery.query('#selectorComptadors')[0].setHidden(false);
        Ext.ComponentQuery.query('#llistaSeleccio')[0].setHidden(true);
        Ext.ComponentQuery.query('#textSelFeta')[0].setHtml('');
    }

});