/*
 * File: app/model/vialerModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LECTCOMP.model.vialerModel', {
    extend: 'Ext.data.Model',
    alias: 'model.vialermodel',

    config: {
        fields: [
            {
                name: 'idCarrer',
                type: 'int'
            },
            {
                name: 'codiCarrer',
                type: 'string'
            },
            {
                name: 'nomCarrer',
                type: 'string'
            },
            {
                name: 'nomCarrerVia',
                type: 'string'
            }
        ]
    }
});